apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongodb-controller
  namespace: 4ceed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo:3.2.1
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: temporary-storage
          mountPath: "/data/db"
      volumes:
        - name: temporary-storage
          emptyDir: {}
        - name: persistent-storage
          hostPath:
            path: "/mnt/nfs/mongodb" 
